#Name of the workflow
name: Destroy MGR Environment

#Triggers to run the workflow
on:
  workflow_dispatch: #To trigger workflow manually using GUI
    inputs:
        booking:
          description: 'Destroy Bookings: [yes/no]'
          required: true
          default: 'no'
        coupon:
          description: 'Destroy Coupons: [yes/no]'
          required: true
          default: 'no'
        infrastructure:
          description: 'Destroy Infrastructure: [yes/no]'
          required: true
          default: 'no'

jobs:
  # Destroy Job
  destroy:
    name: Destroy MGR Resources # Name of the job
    runs-on: ubuntu-latest # The type of runner that the job will run on
    environment: # Environment to which the application will be deployed.
      name: destroy
    steps:
      - name: Checkout #Checkout the Repository into the agent
        uses: actions/checkout@v2

      # This action is developed as an IP by the MCS team to use variable groups present in the .github/variables folder. For more details: https://github.com/marketplace/actions/set-variable
      - name: Set Environment Variables - Organizational Details #Set Variables
        uses: ./.github/actions/set-variable
        with:
          variableFileName: "org-details"

      # Login into your Azure Subscription using your Azure credentials - make sure the credentials has write permissions for the specific resource group/subscription. The credentials should be stored in GitHub Secrets - (Go to Settings Tab ->Secrets)
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          
      # Destroy Bookings Environment
      - name: Azure ARM - Destroy MGR Bookings Resource Groups
        if: github.event.inputs.booking == 'yes'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            rgExists=$(az group exists -n "${{ env.cus_prefix }}-Dojo-Booking-DEV-${{ env.team_suffix }}")
            if [ $rgExists = "true" ]; then 
              az group delete --name "${{ env.cus_prefix }}-Dojo-Booking-DEV-${{ env.team_suffix }}" --yes
            fi
            
            rgExists=$(az group exists -n "${{ env.cus_prefix }}-Dojo-Booking-QA-${{ env.team_suffix }}")
            if [ $rgExists = "true" ]; then 
              az group delete --name "${{ env.cus_prefix }}-Dojo-Booking-QA-${{ env.team_suffix }}" --yes
            fi
            
            rgExists=$(az group exists -n "${{ env.cus_prefix }}-Dojo-Booking-PRD-${{ env.team_suffix }}")
            if [ $rgExists = "true" ]; then 
              az group delete --name "${{ env.cus_prefix }}-Dojo-Booking-PRD-${{ env.team_suffix }}" --yes
            fi
            
            rgExists=$(az group exists -n "${{ env.cus_prefix }}-Dojo-Booking-Log-Analytics-WhiteBelt-${{ env.team_suffix }}")
            if [ $rgExists = "true" ]; then 
              az group delete --name "${{ env.cus_prefix }}-Dojo-Booking-Log-Analytics-WhiteBelt-${{ env.team_suffix }}" --yes
            fi
            
            rgExists=$(az group exists -n "${{ env.cus_prefix }}-Dojo-Booking-Storage-${{ env.team_suffix }}")
            if [ $rgExists = "true" ]; then 
              az group delete --name "${{ env.cus_prefix }}-Dojo-Booking-Storage-${{ env.team_suffix }}" --yes
            fi
            
      # Destroy Coupons Environment
      - name: Azure ARM - Destroy MGR Coupons Resource Groups
        if: github.event.inputs.coupon == 'yes'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            rgExists=$(az group exists -n "${{ env.cus_prefix }}-Dojo-Coupon-DEV-${{ env.team_suffix }}")
            if [ $rgExists = "true" ]; then 
              az group delete --name "${{ env.cus_prefix }}-Dojo-Coupon-DEV-${{ env.team_suffix }}" --yes
            fi
            
            rgExists=$(az group exists -n "${{ env.cus_prefix }}-Dojo-Coupon-QA-${{ env.team_suffix }}")
            if [ $rgExists = "true" ]; then 
              az group delete --name "${{ env.cus_prefix }}-Dojo-Coupon-QA-${{ env.team_suffix }}" --yes
            fi
            
            rgExists=$(az group exists -n "${{ env.cus_prefix }}-Dojo-Coupon-PRD-${{ env.team_suffix }}")
            if [ $rgExists = "true" ]; then 
              az group delete --name "${{ env.cus_prefix }}-Dojo-Coupon-PRD-${{ env.team_suffix }}" --yes
            fi
            
            rgExists=$(az group exists -n "${{ env.cus_prefix }}-Dojo-Coupon-Log-Analytics-${{ env.team_suffix }}")
            if [ $rgExists = "true" ]; then 
              az group delete --name "${{ env.cus_prefix }}-Dojo-Coupon-Log-Analytics-${{ env.team_suffix }}" --yes
            fi
            
            rgExists=$(az group exists -n "${{ env.cus_prefix }}-Dojo-Coupon-Local-${{ env.team_suffix }}")
            if [ $rgExists = "true" ]; then 
             az group delete --name "${{ env.cus_prefix }}-Dojo-Coupon-Local-${{ env.team_suffix }}" --yes
            fi

      # Destroy IAC Environment
      - name: Azure ARM - Destroy MGR IAC Resource Groups
        if: github.event.inputs.infrastructure == 'yes'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            rgExists=$(az group exists -n "${{ env.cus_prefix }}-Dojo-IAC-prd-${{ env.team_suffix }}")
            if [ $rgExists = "true" ]; then 
              az group delete --name "${{ env.cus_prefix }}-Dojo-IAC-prd-${{ env.team_suffix }}" --yes
            fi
            
            rgExists=$(az group exists -n "${{ env.cus_prefix }}-Dojo-terraform-prd-${{ env.team_suffix }}")
            if [ $rgExists = "true" ]; then 
              az group delete --name "${{ env.cus_prefix }}-Dojo-terraform-prd-${{ env.team_suffix }}" --yes
            fi
            
            az monitor diagnostic-settings delete --name "${{ env.cus_prefix }}-diagnostic-profile-${{ env.team_suffix }}" --resource "/subscriptions/${{ env.SUB_ID }}"
